language: c

sudo: false

os:
  - linux
  - osx

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update &&
      brew install qt5 &&
      brew install sdl &&
      export QT5_PREFIX="`brew --prefix qt5`";
      export QMAKE="$QT5_PREFIX/bin/qmake";
    fi
  - if [ ! -f deps/bass24.zip ]; then
        mkdir -p deps && (
            cd deps &&
            wget http://www.un4seen.com/files/bass24-$TRAVIS_OS_NAME.zip -O bass24.zip
        )
    fi &&
    mkdir examples/include &&
    mkdir examples/lib &&
    unzip -d bass24 deps/bass24.zip &&
    cp bass24/bass.h examples/include/;
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      cp bass24/libbass.dylib examples/lib/;
    fi;
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      cp bass24/x64/libbass.so examples/lib/;
    fi
  - if [ -n "$TRAVIS_TAG" ]; then
      export VERSION_TAG=${TRAVIS_TAG:1};
    else
      export VERSION_TAG=$TRAVIS_BRANCH;
    fi

script:
  - make &&
    make examples/example_bass &&
    make examples/example_bass-player

cache:
  directories:
    - deps

addons:
  apt:
    packages:
      - qt5-default
      - libsdl1.2-dev

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      (cd editor &&
      "$QT5_PREFIX/bin/macdeployqt" editor.app &&
      prefix="`grealpath $QT5_PREFIX`";
      frameworks=(editor.app/Contents/Frameworks/Qt*.framework) &&
      frameworks=("${frameworks[@]#editor.app/Contents/Frameworks/}") &&
      frameworks=("${frameworks[@]%.framework}") &&
      for framework in "${frameworks[@]}"; do
        for target in "${frameworks[@]}"; do
          install_name_tool -change $prefix/lib/$target.framework/Versions/5/$target @executable_path/../Frameworks/$target.framework/Versions/5/$target editor.app/Contents/Frameworks/$framework.framework/$framework;
        done;
      done;
      for plugin in editor.app/Contents/PlugIns/*/*.dylib; do
        for target in "${frameworks[@]}"; do
          install_name_tool -change $prefix/lib/$target.framework/Versions/5/$target @executable_path/../Frameworks/$target.framework/Versions/5/$target $plugin;
        done;
      done;
      zip -r rocket-editor-$VERSION_TAG-$TRAVIS_OS_NAME.zip editor.app)
    fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "smP4y0yIKofqJSWDx+gR+LcEulk027oI/FSXJYWz1x345tFV+s3ASRIwdlFxxiqJnOTbcmvI1jK0Un1w5f2o6/QWBNx8f3YXSONHE+BozN6bvM55iADPWDAvsVI/XOlMJ0Tzd+Tek1DwfJsewPmCmBWuSrRhOOA+lkP9deV0mqk="
  file: editor/rocket-editor-$VERSION_TAG-$TRAVIS_OS_NAME.zip
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
